### Create Order

POST http://localhost:8080/odata/v4/OrdersService/Orders
Content-Type: application/json
Authorization: Basic klaus:pass_klaus
{
  "items": [
    {
      "book_ID": "abed2f7a-c50e-4bc5-89fd-9a00a54b4b16",
      "amount": 2
    }
  ]
}

### Read Book

GET http://localhost:8080/odata/v4/BooksService/Books(abed2f7a-c50e-4bc5-89fd-9a00a54b4b16)
Accept: application/json
uthorization: Basic klaus:pass_klaus

